//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFClient.SimpleUsernameServiceDemoSVC {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SimpleUsernameServiceDemoSVC.ISimpleUsernameServiceDemo")]
    public interface ISimpleUsernameServiceDemo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleUsernameServiceDemo/DoWork", ReplyAction="http://tempuri.org/ISimpleUsernameServiceDemo/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleUsernameServiceDemo/TestRoleAdmin", ReplyAction="http://tempuri.org/ISimpleUsernameServiceDemo/TestRoleAdminResponse")]
        void TestRoleAdmin();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleUsernameServiceDemo/TestRoleAPI", ReplyAction="http://tempuri.org/ISimpleUsernameServiceDemo/TestRoleAPIResponse")]
        void TestRoleAPI();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISimpleUsernameServiceDemoChannel : WCFClient.SimpleUsernameServiceDemoSVC.ISimpleUsernameServiceDemo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SimpleUsernameServiceDemoClient : System.ServiceModel.ClientBase<WCFClient.SimpleUsernameServiceDemoSVC.ISimpleUsernameServiceDemo>, WCFClient.SimpleUsernameServiceDemoSVC.ISimpleUsernameServiceDemo {
        
        public SimpleUsernameServiceDemoClient() {
        }
        
        public SimpleUsernameServiceDemoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SimpleUsernameServiceDemoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimpleUsernameServiceDemoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimpleUsernameServiceDemoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public void TestRoleAdmin() {
            base.Channel.TestRoleAdmin();
        }
        
        public void TestRoleAPI() {
            base.Channel.TestRoleAPI();
        }
    }
}
