//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFClient.InvokerServiceDemoSVC {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InvokerServiceDemoSVC.IInvokerServiceDemo")]
    public interface IInvokerServiceDemo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvokerServiceDemo/DoWork", ReplyAction="http://tempuri.org/IInvokerServiceDemo/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvokerServiceDemo/DoWorkNoPermission", ReplyAction="http://tempuri.org/IInvokerServiceDemo/DoWorkNoPermissionResponse")]
        void DoWorkNoPermission();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInvokerServiceDemoChannel : WCFClient.InvokerServiceDemoSVC.IInvokerServiceDemo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InvokerServiceDemoClient : System.ServiceModel.ClientBase<WCFClient.InvokerServiceDemoSVC.IInvokerServiceDemo>, WCFClient.InvokerServiceDemoSVC.IInvokerServiceDemo {
        
        public InvokerServiceDemoClient() {
        }
        
        public InvokerServiceDemoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InvokerServiceDemoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InvokerServiceDemoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InvokerServiceDemoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public void DoWorkNoPermission() {
            base.Channel.DoWorkNoPermission();
        }
    }
}
