//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFClient.ServiceDemoSVC {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomFault", Namespace="http://schemas.datacontract.org/2004/07/WCFServer.ErrorHandling")]
    [System.SerializableAttribute()]
    public partial class CustomFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdditionalDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdditionalData {
            get {
                return this.AdditionalDataField;
            }
            set {
                if ((object.ReferenceEquals(this.AdditionalDataField, value) != true)) {
                    this.AdditionalDataField = value;
                    this.RaisePropertyChanged("AdditionalData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceDemoSVC.IServiceDemo")]
    public interface IServiceDemo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDemo/DoWork", ReplyAction="http://tempuri.org/IServiceDemo/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDemo/ThrowException", ReplyAction="http://tempuri.org/IServiceDemo/ThrowExceptionResponse")]
        void ThrowException(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDemo/ThrowCustomException", ReplyAction="http://tempuri.org/IServiceDemo/ThrowCustomExceptionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFClient.ServiceDemoSVC.CustomFault), Action="http://tempuri.org/IServiceDemo/ThrowCustomExceptionCustomFaultFault", Name="CustomFault", Namespace="http://schemas.datacontract.org/2004/07/WCFServer.ErrorHandling")]
        void ThrowCustomException(string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceDemoChannel : WCFClient.ServiceDemoSVC.IServiceDemo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceDemoClient : System.ServiceModel.ClientBase<WCFClient.ServiceDemoSVC.IServiceDemo>, WCFClient.ServiceDemoSVC.IServiceDemo {
        
        public ServiceDemoClient() {
        }
        
        public ServiceDemoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceDemoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDemoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDemoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public void ThrowException(string message) {
            base.Channel.ThrowException(message);
        }
        
        public void ThrowCustomException(string message) {
            base.Channel.ThrowCustomException(message);
        }
    }
}
